FROM atlassian/bitbucket-server:4.14
COPY bitbucket.properties /var/atlassian/application-data/bitbucket/shared/
#COPY db.h2.db /var/atlassian/application-data/bitbucket/shared/data/
#ADD  git-lfs /var/atlassian/application-data/bitbucket/shared/data/git-lfs
